[Definition]
failregex = .*"remoteAddr":"<HOST>".*"message":"Login failed:.*
            .*"remoteAddr":"<HOST>".*"message":"Trusted domain error.*
ignoreregex =
datepattern = "time"\s*:\s*"%%Y-%%m-%%dT%%H:%%M:%%S
