[nextcloud]
enabled  = true
port     = http,https,11000
filter   = nextcloud
logpath  = /var/ncdata/nextcloud.log
maxretry = 5
findtime = 10m
bantime  = 1h
action   = iptables-multiport[name=nextcloud, port="http,https,11000", protocol=tcp]

[apache-auth]
enabled  = true
port     = http,https,11000
filter   = apache-auth
logpath  = /var/log/apache2/nextcloud_error.log
maxretry = 5
findtime = 10m
bantime  = 1h

[apache-badbots]
enabled  = true
port     = http,https,11000
filter   = apache-badbots
logpath  = /var/log/apache2/nextcloud_access.log
maxretry = 2
findtime = 10m
bantime  = 24h

[sshd]
enabled  = true
port     = ssh
filter   = sshd
logpath  = /var/log/auth.log
maxretry = 5
findtime = 10m
bantime  = 1h
